#!/usr/bin/env python3
# pylint: disable=missing-docstring

import csv
import heapq
import sys
from urllib.parse import urlparse

import bson
import bson.json_util as json
import click
from pymongo import MongoClient
from pymongo.read_concern import ReadConcern

import mutils


def make_cluster_oplog_cursor(uri: str, start: bson.Timestamp, end: bson.Timestamp, excluded: list):
    parsed = urlparse(uri)

    conn = MongoClient(uri)
    if not conn.is_mongos:
        return oplog_cursor(conn, start, end, excluded)

    shard_map = conn["admin"].command("getShardMap").get("map")
    conn.close()

    cursors = {}
    for shard_uri in shard_map.values():
        rs_name, hosts = shard_uri.split("/", 1)
        rs_uri = f"mongodb://{parsed.username}:{parsed.password}@{hosts}"
        cursors[rs_name] = oplog_cursor(MongoClient(rs_uri), start, end, excluded)

    return _merge_cursors(cursors)


def oplog_cursor(conn: MongoClient, start: bson.Timestamp, end: bson.Timestamp, excluded: list):
    query = {
        "op": {"$ne": "n"},
        "ns": {
            "$nin": ["config.mongos", "config.system.sessions"],
            "$not": {"$regex": "^config.cache"},
        },
    }

    cond = {}
    if start:
        cond["$gte"] = start
    if end:
        cond["$lte"] = end
    if cond:
        query["ts"] = cond

    with conn:
        rs_name = conn.admin.command("hello")["setName"]
        oplog_rs = conn["local"].get_collection("oplog.rs", read_concern=ReadConcern("local"))
        for doc in oplog_rs.find(query):
            if doc["ns"] in excluded:
                continue
            doc["rs"] = rs_name
            yield doc


def _merge_cursors(rss):
    class Orderable:
        def __init__(self, doc):
            self.d = doc

        def __eq__(self, o):
            return self.d["ts"] == o.d["ts"]

        def __lt__(self, o):
            return self.d["ts"] < o.d["ts"]

    q = []

    for rs, cur in rss.items():
        try:
            doc = next(cur)
            q.append(Orderable(doc))
        except StopIteration:
            pass
    heapq.heapify(q)

    while len(q) != 0:
        doc = heapq.heappop(q).d
        rs = doc["rs"]
        yield doc

        try:
            doc = next(rss[rs])
            heapq.heappush(q, Orderable(doc))
        except StopIteration:
            del rss[rs]


class TimestampParamType(click.ParamType):
    name = "BSON timestamp"

    def convert(self, value, param, ctx):
        if isinstance(value, bson.Timestamp):
            return value

        try:
            time, inc = value.split(".", 1)
            return bson.Timestamp(int(time), int(inc))
        except:  # pylint: disable=bare-except
            self.fail(f"{value!r} is not a valid timestamp", param, ctx)


@click.command()
@click.option(
    "--uri",
    default="localhost:27017",
    envvar="MONGODB_URI",
    help="MongoDB URI. Default: localhost:27017.",
)
@click.option(
    "-o",
    "--out",
    default=sys.stdout,
    type=click.File("w", lazy=True),
    help="Output file. Default: stdout.",
)
@click.option(
    "-s",
    "--start",
    type=TimestampParamType(),
    help="Min oplog ts ($gte).",
)
@click.option(
    "-e",
    "--end",
    type=TimestampParamType(),
    help="Max oplog ts ($lte).",
)
@click.option(
    "--exclude",
    default="Namespaces to exclude.",
)
@click.option(
    "--json",
    is_flag=True,
    help="Produce output as MongoDB Extended JSON v2.",
)
def command(uri, **kwargs):
    if not uri.startswith("mongodb://"):
        uri = f"mongodb://{uri}"

    excluded = mutils.NSMatcher(kwargs["exclude"].split(","))
    oplog = make_cluster_oplog_cursor(uri, kwargs["start"], kwargs["end"], excluded)

    if kwargs["json"]:
        out = kwargs["out"]
        out.write("[\n")
        for doc in oplog:
            out.write(json.dumps(doc) + ",\n")
        out.write("]")
        return

    w = csv.DictWriter(
        kwargs["out"],
        fieldnames=["ts", "rs", "ns", "op", "o"],
        extrasaction="ignore",
        lineterminator="\n",
    )

    for doc in oplog:
        w.writerow(
            {
                "ts": f'{doc["ts"].time}.{doc["ts"].inc}',
                "rs": doc.get("rs"),
                "ns": doc["ns"],
                "op": doc["op"],
                "o": json.dumps(doc["o"]),
            }
        )


if __name__ == "__main__":
    from signal import SIG_DFL, SIGPIPE, signal

    signal(SIGPIPE, SIG_DFL)

    command()  # pylint: disable=no-value-for-parameter
