#!/usr/bin/env python3
# pylint: disable=missing-docstring

import hashlib
import sys
from urllib.parse import urlparse

import bson
import bson.json_util as json
import click
from pymongo import MongoClient


def dump_replset(conn: MongoClient, with_docs: bool) -> tuple[dict, dict[dict]]:
    rs_name = conn.admin.command("hello")["setName"]

    infos = {}
    all_docs = {}
    for db_info in conn.list_databases():
        db_name = db_info["name"]
        if db_name == "local":
            continue

        db = conn[db_name]
        db_hash = db.command("dbHash")
        for coll in db.list_collections():
            coll_name = coll["name"]

            if coll["type"] == "collection":
                coll["info"]["uuid"] = coll["info"]["uuid"].hex()

            info = {
                "ns": f"{db_name}.{coll_name}",
                "spec": coll,
            }
            if coll["type"] == "collection":
                info["dbHash"] = db_hash["collections"][coll_name]

            if can_save_docs(db_name, coll_name):
                docs = list(db[coll_name].find())
                info["count"] = len(docs)

                if with_docs:
                    all_docs[f"{rs_name}:{db_name}.{coll_name}"] = docs

            infos[f"{rs_name}:{db_name}.{coll_name}"] = info

    return infos, all_docs


def can_save_docs(db_name: str, coll_name: str) -> bool:
    if db_name == "admin":
        return coll_name != "system.keys"
    elif db_name == "config":
        if coll_name == "mongos" or coll_name.startswith("cache."):
            return False
    if coll_name.startswith("system.buckets."):
        return True

    return not coll_name.startswith("system.")


def from_user_view(conn: MongoClient, nss: dict, with_docs: bool) -> tuple[dict, dict]:
    briefs, all_docs = {}, {}

    for ns in nss.keys():
        _, ns_name = ns.split(":", 1)
        db_name, coll_name = ns_name.split(".", 1)
        if not can_save_docs(db_name, coll_name):
            continue

        md5, docs = hashlib.md5(usedforsecurity=False), []
        for doc in conn[db_name][coll_name].find_raw_batches():
            md5.update(doc)
            docs.extend(bson.decode_all(doc))

        if len(docs) != 0:
            briefs[ns] = {"md5": md5.hexdigest(), "count": len(docs)}
        else:
            briefs[ns] = {"md5": "", "count": 0}

        if with_docs:
            all_docs[":" + ns_name] = docs

    return briefs, all_docs


@click.command()
@click.option("--uri", envvar="MONGODB_URI", default="mongodb://localhost:27017")
@click.option("--with-docs", is_flag=True)
def command(uri: str, with_docs: bool):
    if not uri.startswith("mongodb://"):
        uri = f"mongodb://{uri}"

    with MongoClient(uri) as conn:
        parsed = urlparse(uri)
        if not conn.is_mongos:
            all_infos, _ = dump_replset(conn, with_docs=False)
            brief, docs = from_user_view(conn, all_infos, with_docs)
            rv = {"nss": all_infos, "brief": brief}
            if with_docs:
                rv["docs"] = docs

            sys.stdout.write(json.dumps(rv))
            return

        all_infos = {}
        all_docs = {}
        shard_map = conn["admin"].command("getShardMap")["map"]
        for shard_uri in shard_map.values():
            rs_hosts = shard_uri.split("/", 1)[1]
            rs_uri = f"mongodb://{parsed.username}:{parsed.password}@{rs_hosts}"
            with MongoClient(rs_uri) as rs_conn:
                infos, docs = dump_replset(rs_conn, with_docs)
                all_infos.update(infos)
                all_docs.update(docs)

        brief, docs = from_user_view(conn, all_infos, with_docs)
        all_docs.update(docs)
        rv = {"nss": all_infos, "brief": brief}
        if with_docs:
            rv["all_docs"] = all_docs

    sys.stdout.write(json.dumps(rv))


if __name__ == "__main__":
    from signal import SIG_DFL, SIGPIPE, signal

    signal(SIGPIPE, SIG_DFL)

    command()  # pylint: disable=no-value-for-parameter
