#!/usr/bin/env python3
# pylint: disable=missing-docstring

import hashlib
import sys
from urllib.parse import urlparse

import bson
import bson.json_util as json
import click
from pymongo import MongoClient

import mutils


def dump_replset(
    conn: MongoClient,
    with_docs: bool,
    excluded: mutils.NSMatcher,
) -> tuple[dict, dict[dict]]:
    rs_name = conn.admin.command("hello")["setName"]

    infos = {}
    all_docs = {}
    for db_info in conn.list_databases():
        db_name = db_info["name"]
        db = conn[db_name]
        db_hash = db.command("dbHash")
        for coll in db.list_collections():
            coll_name = coll["name"]
            ns = f"{db_name}.{coll_name}"
            if ns in excluded:
                continue

            if coll["type"] == "collection":
                coll["info"]["uuid"] = coll["info"]["uuid"].hex()

            info = {
                "ns": ns,
                "spec": coll,
            }
            if coll["type"] == "collection":
                info["dbHash"] = db_hash["collections"].get(coll_name, "")

            if should_view_spec(db_name, coll_name):
                docs = list(db[coll_name].find())
                info["count"] = len(docs)

                if with_docs:
                    docs.sort(key=mutils.doc_sort_key)
                    all_docs[f"{rs_name}:{ns}"] = docs

            infos[f"{rs_name}:{ns}"] = info

    return infos, all_docs


def is_system_collection(coll_name: str) -> bool:
    return coll_name.startswith("system.")


def is_timeseries_bucket(coll_name: str) -> bool:
    return coll_name.startswith("system.buckets.")


def should_view_spec(db_name: str, coll_name: str) -> bool:
    match db_name:
        case "local":
            return False
        case "admin":
            return coll_name != "system.keys"

    return is_timeseries_bucket(coll_name) or not is_system_collection(coll_name)


def should_view_docs(db_name: str, coll_name: str) -> bool:
    match db_name:
        case "local":
            return False
        case "admin":
            return coll_name in mutils.admin_collections
        case "config":
            return coll_name in mutils.config_collections

    return is_timeseries_bucket(coll_name) or not is_system_collection(coll_name)


def from_user_view(conn: MongoClient, nss: dict, with_docs: bool) -> tuple[dict, dict]:
    briefs, all_docs = {}, {}

    for ns in nss.keys():
        ns_name = ns.split(":", 1)[1]
        db_name, coll_name = ns_name.split(".", 1)
        if not should_view_docs(db_name, coll_name):
            continue

        md5, docs = hashlib.md5(), []
        for doc in conn[db_name][coll_name].find_raw_batches():
            md5.update(doc)
            docs.extend(bson.decode_all(doc))

        if docs:
            briefs[ns] = {"md5": md5.hexdigest(), "count": len(docs)}
        else:
            briefs[ns] = {"md5": "", "count": 0}

        if with_docs:
            docs.sort(key=mutils.doc_sort_key)
            all_docs[":" + ns_name] = docs

    return briefs, all_docs


@click.command()
@click.option("--uri", envvar="MONGODB_URI", default="mongodb://localhost:27017")
@click.option("--with-docs", is_flag=True)
@click.option("--with-system", is_flag=True)
@click.option("--exclude", default="")
def command(uri: str, **kwargs):
    if not uri.startswith("mongodb://"):
        uri = f"mongodb://{uri}"

    with_docs = kwargs.get("with_docs", False)
    excluded = mutils.NSMatcher(kwargs.pop("exclude", "").split(","))

    with MongoClient(uri) as conn:
        all_infos, all_docs = {}, {}
        if not conn.is_mongos:
            all_infos, _ = dump_replset(conn, False, excluded)
        else:
            parsed = urlparse(uri)
            shard_map = conn["admin"].command("getShardMap")["map"]
            for shard_uri in shard_map.values():
                rs_hosts = shard_uri.split("/", 1)[1]
                rs_uri = f"mongodb://{parsed.username}:{parsed.password}@{rs_hosts}"
                with MongoClient(rs_uri) as rs_conn:
                    infos, docs = dump_replset(rs_conn, with_docs, excluded)
                    all_infos.update(infos)
                    if with_docs:
                        all_docs.update(docs)

        brief, docs = from_user_view(conn, all_infos, with_docs)
        rv = {"nss": all_infos, "brief": brief}
        if with_docs:
            all_docs.update(docs)
            rv["docs"] = all_docs

    if not kwargs.get("with_system", False):
        rv = mutils.mtrim(rv)
    sys.stdout.write(json.dumps(rv))


if __name__ == "__main__":
    from signal import SIG_DFL, SIGPIPE, signal

    signal(SIGPIPE, SIG_DFL)

    command()  # pylint: disable=no-value-for-parameter
